# Generated by Django 5.1.1 on 2024-09-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imgsrc',
            field=models.CharField(default='/static/images/best-product/B1-1.png', max_length=200),
        ),
    ]
