# Generated by Django 5.1.1 on 2024-09-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
        ),
    ]
